### ISSUE TITLE
Code formatter button?

### ISSUE THREAD

**Issue by mvattuone** [mazelife/django-redactor#14]
Hi,

Wondering if Django Redactor has any sort of a code formatting option that I am overlooking?  We have certain clients that have had issues with text changing randomly, and they would prefer to have an option to remove all code Redactor adds automatically.

I tried the following to see if we could just disable automatic formatting and let people write their own HTML, but this didn't work:

```
    widgets = {
        'tease':AdminRedactorEditor(redactor_settings={'autoformat': False }),
        'image_override':Textarea(),
        'tags':TagAutocomplete(),
    }
```

Any ideas?  If the option doesn't exist or is deprecated, we could try to create our own custom solution.

**Comment by mazelife** [comment]
I took a look at the django-redactor code and everything works as you'd expect. If you pass `redactor_settings={'autoformat': False }` into the widget constructor, that gets translated through to the javascript `Redactor` object constructor. From a quick perusal of the Redactor JavaScript [source](https://github.com/mazelife/django-redactor/blob/master/redactor/static/django-redactor/redactor/redactor.js), it looks like autoformat just replaces line breaks with `<p>` tags. It's also not documented  in the [settings](http://imperavi.com/redactor/docs/settings/) page. I'm not sure if that's because it's deprecated or what. The setting you probably want to use is `{"cleanup": True}`. The redactor docs say that this "turns on/off a text's cleanup on paste," which is somewhat cryptic, but looking at the source code, it appears to me that this might be closer to what you want.
